services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual (.)
    build: .
    # Nome do container para fácil identificação
    container_name: heitorzinho
    # Mapeia a porta 8000 do seu computador para a porta 8000 do container
    ports:
      - "8000:8000"
    # Monta o diretório atual no diretório /app do container
    # Isso permite o live-reloading do código e a persistência do banco de dados SQLite
    volumes:
      - .:/app